#!/bin/bash
# extracts the target values by position from a given data file (i.e. '$1') using search parameters (i.e. '$2' onwards)
# last update: 2021-07-03

printhelp() {
  echo ""
  echo " Usage:    ofcatchDataFromBlock <data-file> <\"block-start\"> <\"block-end\"> <\"target-string\"> <position>"
  echo ""
  echo " Examples: ofcatchDataFromBlock log \"^Time =\" \"^ExecutionTime =\" \"^Time =\" 3"
  echo ""
exit 1
}

grepbloc() {
cat $1 | sed -n "/$2/,/$3/p"
}

grepline() {
cat $1 | sed -n "/$2/,/$3/p" | grep "$4"
}

grepvalu() {
cat $1 | sed -n "/$2/,/$3/p" | grep "$4" | sed 's/  */ /g' | cut -d' ' -f"$5" | tr -d ','
}

case $# in
  5)
    echo "$(grepvalu "$1" "$2" "$3" "$4" "$5")"
    ;;
  4)
    echo "$(grepline "$1" "$2" "$3" "$4")"
    ;;
  3)
    echo "$(grepbloc "$1" "$2" "$3")"
    ;;
  *)
    printhelp
    ;;
esac

